# Étape 1 : Builder Maven avec Java 17
FROM maven:3.9.2-eclipse-temurin-17 AS builder
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

# Étape 2 : Exécuter l'application avec Java 17
FROM openjdk:17-jdk-slim
WORKDIR /app
COPY --from=builder /app/target/rental-backend-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8080
CMD ["java", "-jar", "app.jar"]
